name: PhantomCore
version: ${project.version}
api-version: '1.15'
description: ${project.description}
authors:
  - lokka30 (Author)
  - JavaFactory (LightningStorage Lib)
  - bStats Team (bStats Lib)

main: io.github.lokka30.phantomcore.PhantomCore

commands:
  vanish:
    description: Become invisible to other players.
    usage: /<command> [player] [on/off]
  setwarp:
    description: Set a warp to the centre of your current location.
    usage: /<command> <warp name>
  delwarp:
    description: Delete a warp.
    usage: /<command> <warp name>
  warp:
    description: Teleport to a warp.
    usage: /<command> <warp name> [player]
  near:
    description: View nearby players (within 200 blocks).
    usage: /<command> [player]
  invsee:
    description: View the inventory of an online player.
    usage: /<command> <player>
  flyspeed:
    description: Set your fly speed.
    usage: /<command> <speed 0-10>
  walkspeed:
    description: Set your walk speed.
    usage: /<command> <speed 0-10>
  clearinventory:
    description: Clear your inventory.
    usage: /<command> [player]
  broadcast:
    description: Broadcast a message to the server.
    usage: /<command> <message>
  fly:
    description: Toggle if you are allowed to fly.
    usage: /<command> [on/off] [player]

permissions:
  phantomcore.delwarp:
    default: op
  phantomcore.invsee:
    default: op
  phantomcore.near:
    default: true
  phantomcore.near.others:
    default: op
  phantomcore.vanish:
    default: op
  phantomcore.vanish.others:
    default: op
  phantomcore.warp:
    default: true
  phantomcore.warp.others:
    default: op
  phantomcore.broadcast:
    default: op
  phantomcore.clearinventory:
    default: op
  phantomcore.clearinventory.others:
    default: op
  phantomcore.flyspeed:
    default: op
  phantomcore.flyspeed.others:
    default: op
  phantomcore.walkspeed:
    default: op
  phantomcore.walkspeed.others:
    default: op