# Should all teleportations (warps, spawn, tpa) teleport the player to the exact centre of the block?
# Suggested: Yes, so players aren't accidentally standing in lava as well (for example).
teleport-to-centre: true

# When looking for a player's target block, what is the maximum range?
# Suggested: 100-200
target-block-range: 100

file-version: 3